// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTMS.Data.Context;

#nullable disable

namespace SMTMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219035023_AddFileHash")]
    partial class AddFileHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SMTMS.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoScanOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModsDirectory")
                        .HasColumnType("TEXT");

                    b.Property<int>("WindowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SMTMS.Core.Models.GitDiffCache", b =>
                {
                    b.Property<string>("CommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedDiffData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CommitHash");

                    b.HasIndex("CreatedAt");

                    b.ToTable("GitDiffCache");
                });

            modelBuilder.Entity("SMTMS.Core.Models.ModMetadata", b =>
                {
                    b.Property<string>("UniqueID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMachineTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNexusCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTranslationUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusDescription")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NexusDownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NexusEndorsementCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NexusImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueID");

                    b.HasIndex("LastTranslationUpdate");

                    b.HasIndex("RelativePath");

                    b.ToTable("ModMetadata");
                });

            modelBuilder.Entity("SMTMS.Core.Models.TranslationMemory", b =>
                {
                    b.Property<string>("SourceHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceHash");

                    b.HasIndex("Engine");

                    b.HasIndex("Timestamp");

                    b.ToTable("TranslationMemory");
                });
#pragma warning restore 612, 618
        }
    }
}
