// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTMS.Data.Context;

#nullable disable

namespace SMTMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120055152_AddNexusIdToMetadata")]
    partial class AddNexusIdToMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SMTMS.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoScanOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModsDirectory")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationApiType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationSourceLang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationTargetLang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WindowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SMTMS.Core.Models.HistorySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMods")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistorySnapshots");
                });

            modelBuilder.Entity("SMTMS.Core.Models.ModMetadata", b =>
                {
                    b.Property<string>("UniqueID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMachineTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNexusIdUserAdded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFileHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNexusCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTranslationUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusDescription")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NexusDownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NexusEndorsementCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NexusId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueID");

                    b.HasIndex("LastTranslationUpdate");

                    b.HasIndex("RelativePath");

                    b.ToTable("ModMetadata");
                });

            modelBuilder.Entity("SMTMS.Core.Models.ModTranslationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModUniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModUniqueId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("ModUniqueId", "SnapshotId");

                    b.ToTable("ModTranslationHistories");
                });

            modelBuilder.Entity("SMTMS.Core.Models.TranslationMemory", b =>
                {
                    b.Property<string>("SourceHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceHash");

                    b.HasIndex("Engine");

                    b.HasIndex("Timestamp");

                    b.ToTable("TranslationMemory");
                });

            modelBuilder.Entity("SMTMS.Core.Models.ModTranslationHistory", b =>
                {
                    b.HasOne("SMTMS.Core.Models.ModMetadata", "ModMetadata")
                        .WithMany()
                        .HasForeignKey("ModUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTMS.Core.Models.HistorySnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModMetadata");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
