// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTMS.Data.Context;

#nullable disable

namespace SMTMS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SMTMS.Core.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoScanOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModsDirectory")
                        .HasColumnType("TEXT");

                    b.Property<int>("WindowHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SMTMS.Core.Models.ModMetadata", b =>
                {
                    b.Property<string>("UniqueID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMachineTranslated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNexusCheck")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTranslationUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusDescription")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NexusDownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NexusEndorsementCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NexusImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NexusSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCategory")
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueID");

                    b.ToTable("ModMetadata");
                });

            modelBuilder.Entity("SMTMS.Core.Models.TranslationMemory", b =>
                {
                    b.Property<string>("SourceHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceHash");

                    b.ToTable("TranslationMemory");
                });
#pragma warning restore 612, 618
        }
    }
}
